title: arknights-mower
lang: zh-Hans
description: 7*24 小时不间断长草，让你忘掉这个游戏！

plugins:
  - jekyll-remote-theme

remote_theme: ZhaoZuohong/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
