title: arknigths-mower
lang: en
description: 7*24 小时不间断长草，让你忘掉这个游戏！

theme: just-the-docs

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
