title: arknights-mower
lang: zh-Hans
description: 《明日方舟》长草助手

plugins:
  - jekyll-remote-theme

remote_theme: ArkMowers/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

mermaid:
  custom: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
